#include "ViewportInteractionV2/PencilInteractionHandler.h"
#include <algorithm>
#include <cmath>
namespace VoxelForge::Editor::InteractionV2
{
using Position = Asset::Voxel::VoxelPosition;
bool PencilInteractionHandler::CanAccept(const PencilInteractionInput& i,const PencilGestureSession& s) const noexcept { return !i.FocusLost && !i.CameraActive && (s.OwnsPointer() || (i.ViewportHovered&&i.ViewportFocused&&!i.UiCapturesPointer)); }
bool PencilInteractionHandler::Begin(PencilGestureSession& s,const std::uint64_t id,PencilCompactRequest r,const PencilInteractionInput& i) { if(s.OwnsPointer()||!CanAccept(i,s)) return false; s.Begin(id,std::move(r)); return true; }
bool PencilInteractionHandler::Key::operator==(const Key& o) const noexcept { return center==o.center && request.Dimensions.X==o.request.Dimensions.X && request.Dimensions.Y==o.request.Dimensions.Y && request.Dimensions.Z==o.request.Dimensions.Z && request.Brush==o.request.Brush && request.Placement.Normal==o.request.Placement.Normal && request.Action==o.request.Action && request.PaletteIndex==o.request.PaletteIndex && request.DocumentGeneration==o.request.DocumentGeneration && request.DocumentRevision==o.request.DocumentRevision && request.ProfileIdentity==o.request.ProfileIdentity && request.ProfileRevision==o.request.ProfileRevision; }
std::size_t PencilInteractionHandler::Hash::operator()(const Key& k) const noexcept { return static_cast<std::size_t>(k.center.X) ^ (static_cast<std::size_t>(k.center.Y)<<11U) ^ (static_cast<std::size_t>(k.center.Z)<<22U) ^ static_cast<std::size_t>(k.request.Brush.Size*31) ^ static_cast<std::size_t>(k.request.DocumentRevision); }
PencilCompactPlanPtr PencilInteractionHandler::CacheOrPlan(SmartToolPlanner& p,PencilCompactRequest r,Position c) { Key key{r,c}; if(auto it=cache_.find(key);it!=cache_.end()) { ++metrics_.PlanCacheHits; return it->second; } ++metrics_.PlanCacheMisses; ++metrics_.BusinessResolveBatches; const auto results=p.PlanPencilCompactBatch(r,{&c,1U}); if(results.empty()||!results.front().HasPlan()) return {}; if(cache_.size()>=MaxCache) cache_.clear(); cache_.emplace(std::move(key),results.front().Plan); ++metrics_.PlanBuilds; ++metrics_.FootprintTranslations; return results.front().Plan; }
PencilCompactPlanPtr PencilInteractionHandler::PlanHover(SmartToolPlanner& p,PencilCompactRequest r,Position c) { return CacheOrPlan(p,std::move(r),c); }
bool PencilInteractionHandler::Drag(PencilGestureSession& s,SmartToolPlanner& p,Position c, const Position normal,const PencilInteractionInput& i) { if(!s.OwnsPointer()||!CanAccept(i,s)) { if(i.FocusLost) s.Cancel(); return false;} const PencilSurfaceSample sample=s.ResolveSurfaceSample(c,normal); if(!sample.StartsNewSurfaceSegment && !s.IsSuspended() && s.LastCenter() && s.LastNormal() && *s.LastCenter()==sample.Center && *s.LastNormal()==sample.Normal) return false; Position start=(sample.StartsNewSurfaceSegment ? std::optional<Position>{} : s.LastCenter()).value_or(sample.Center); const int dx=sample.Center.X-start.X,dy=sample.Center.Y-start.Y,dz=sample.Center.Z-start.Z; const int steps=std::max({std::abs(dx),std::abs(dy),std::abs(dz)}); std::vector<Position> centres; centres.reserve(static_cast<std::size_t>(steps)+1U); for(int n=0;n<=steps;++n) { Position q{static_cast<std::int32_t>(std::lround(start.X+dx*(double)n/std::max(1,steps))),static_cast<std::int32_t>(std::lround(start.Y+dy*(double)n/std::max(1,steps))),static_cast<std::int32_t>(std::lround(start.Z+dz*(double)n/std::max(1,steps)))}; if(!s.HasVisited(q,sample.Normal)) centres.push_back(q); }
 PencilCompactRequest request=s.SourceRequest(); request.Placement.Normal=sample.Normal; std::vector<PencilCompactPlanPtr> plans(centres.size()); std::vector<Position> misses; std::vector<std::size_t> missIndices; misses.reserve(centres.size()); missIndices.reserve(centres.size()); for(std::size_t index=0;index<centres.size();++index) { Key key{request,centres[index]}; if(auto it=cache_.find(key);it!=cache_.end()) { plans[index]=it->second; ++metrics_.PlanCacheHits; } else { misses.push_back(centres[index]); missIndices.push_back(index); ++metrics_.PlanCacheMisses; } }
 if(!misses.empty()) { ++metrics_.BusinessResolveBatches; const auto results=p.PlanPencilCompactBatch(request,misses); for(std::size_t index=0;index<results.size();++index) { if(!results[index].HasPlan()) continue; if(cache_.size()>=MaxCache) cache_.clear(); const std::size_t planIndex=missIndices[index]; plans[planIndex]=results[index].Plan; cache_.emplace(Key{request,misses[index]},results[index].Plan); ++metrics_.PlanBuilds; ++metrics_.FootprintTranslations; } }
 bool appended=false; for(std::size_t index=0;index<centres.size();++index) appended|=s.Append(plans[index],centres[index],sample.Normal); return appended; }
void PencilInteractionHandler::Escape(PencilGestureSession& s) noexcept { s.Cancel(); }
std::size_t PencilInteractionHandler::CacheSize() const noexcept{return cache_.size();}
const PencilInteractionMetrics& PencilInteractionHandler::Metrics() const noexcept{return metrics_;}
} // namespace VoxelForge::Editor::InteractionV2
